// geoffreywild-website-react/src/components/Job.tsx
import React from "react";
import { IJobInfo } from "./models/job.models";
import ResumeDateRange from "./ResumeDateRange";
import ResumeInfoList from "./ResumeInfoList";

interface IJobProps {
    /** Information related to the job */
    jobInfo: IJobInfo;
}

/**
 * Creates a job with related information
 * @param props Contains information about the job
 */
const Job: React.SFC<IJobProps> = (props: IJobProps) => {
    const jobInfo = props.jobInfo;

    return (
        <div>
            <h3>{jobInfo.position}</h3>
            <h4>
                {jobInfo.employer} / {jobInfo.resumeInfo.location} / <ResumeDateRange dateStart={jobInfo.resumeInfo.dateStart} dateEnd={jobInfo.resumeInfo.dateEnd}/>
            </h4> 

            <ResumeInfoList infoList={jobInfo.resumeInfo.infoList} />
        </div>
    );
};

export default Job;

// geoffreywild-website/src/app/job/job.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { IJobInfo } from './job.models';

@Component({
  selector: 'app-job',
  templateUrl: './job.component.html',
})

/**
 * @summary Contains all information for jobs for a resume
 */
export class JobComponent implements OnInit {
  @Input() public jobModel: IJobInfo;
  constructor() { }

  ngOnInit() {
  }

}

<div class="jobEntry">
  <h3>{{jobModel.position}}</h3>
  <h4>
    {{jobModel.employer}} / {{jobModel.resumeInfo.location}} / {{jobModel.resumeInfo.dateStart | date:'MMM yyyy'}}
    <span *ngIf="jobModel.resumeInfo.dateEnd">- {{jobModel.resumeInfo.dateEnd | date:'MMM yyyy'}}</span>
    <span *ngIf="!jobModel.resumeInfo.dateEnd">- Present</span>
  </h4>
  <ul class="responsibilityList">
    <li *ngFor="let responsibility of jobModel.resumeInfo.infoList">
      {{responsibility}}
    </li>
  </ul>
</div>
