// geoffreywild-website/src/app/job/job.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { IJobInfo } from './job.models';

@Component({
  selector: 'app-job',
  templateUrl: './job.component.html',
})
export class JobComponent implements OnInit {
  @Input() public jobModel: IJobInfo;
  constructor() { }

  ngOnInit() {
  }

}

<div class="jobEntry">
  <h3>{{jobModel.position}}</h3>
  <h4>
    {{jobModel.employer}} / {{jobModel.resumeInfo.location}} / {{jobModel.resumeInfo.dateStart | date:'MMM yyyy'}}
    <span *ngIf="jobModel.resumeInfo.dateEnd">- {{jobModel.resumeInfo.dateEnd | date:'MMM yyyy'}}</span>
    <span *ngIf="!jobModel.resumeInfo.dateEnd">- Present</span>
  </h4>
  <ul class="responsibilityList">
    <li *ngFor="let responsibility of jobModel.resumeInfo.infoList">
      {{responsibility}}
    </li>
  </ul>
</div>

// geoffreywild-websit-react/src/components/Job.tsx
import React from "react";
import { IJobInfo } from "./models/job.models";

interface IJobProps {
    jobInfo: IJobInfo;
}

const Job: React.SFC<IJobProps> = (props: IJobProps) => {
    const jobInfo = props.jobInfo;
    const dateFormat = new Intl.DateTimeFormat(["en-US", "en-GB"], {month: "long", year: "numeric"});

    return (
        <div>
            <h3>{jobInfo.position}</h3>
            <h4>
                {jobInfo.employer} / {jobInfo.resumeInfo.location} / {dateFormat.format(jobInfo.resumeInfo.dateStart)}
                <span>{jobInfo.resumeInfo.dateEnd ? `- ${dateFormat.format(jobInfo.resumeInfo.dateEnd)}` : "- Present"}</span>
            </h4> 
            <ul className="responsibilityList">
                {getResumeInfoList(jobInfo.resumeInfo.infoList)}
            </ul>
        </div>
    );
};

function getResumeInfoList(infoList?: string[]): JSX.Element[] | null
{
    if (!infoList) { return null; }

    return infoList.map((info: string, _: number) => {
        return <li>{info}</li>;
    });
}

export default Job;
