// geoffreywild-website/src/app/resume/resume.component.ts
import { Component, OnInit } from '@angular/core';

import { JOBS } from '../../data/jobs';
import { IJobInfo } from '../job/job.models';
import { IEducationInfo } from '../education/education.models';
import { EDUCATION } from 'src/data/education';

@Component({
  selector: 'app-resume',
  templateUrl: './resume.component.html',
  styleUrls: ['./resume.component.scss']
})
export class ResumeComponent implements OnInit {

  public jobs: IJobInfo[] = JOBS;
  public education: IEducationInfo[] = EDUCATION;
  public isWorkSectionCollapsed: boolean;
  public isEducationSectionCollapsed: boolean;

  constructor() {
    this.isWorkSectionCollapsed = true;
    this.isEducationSectionCollapsed = true;
  }

  ngOnInit() {
  }

}

<h1>Resume</h1>

<div>
  <div class="expandButton" (click)="toggleAllSections()">{{toggleText}}</div>
</div>

<div>
  <div class="expandButton" (click)="toggleResumeSection(ResumeSectionType.work)">Work Experience</div>
  <div class="collapsibleSection" *ngIf="!isWorkSectionCollapsed">
    <app-job *ngFor="let job of jobs" [jobModel]="job">
    </app-job>
  </div>
</div>

<div>
  <div class="expandButton" (click)="toggleResumeSection(ResumeSectionType.education)">Education</div>
  <div class="collapsibleSection" *ngIf="!isEducationSectionCollapsed">
    <app-education *ngFor="let eduEntry of education" [educationModel]="eduEntry">
    </app-education>
  </div>
</div>

// geoffreywild-websit-react/src/components/Resume.tsx
import React from "react";

import {EDUCATION} from "../data/education";
import { JOBS } from "../data/jobs";
import { IEducationInfo } from "./models/education.models";
import { IJobInfo } from "./models/job.models";
import Job from "./Job";
import Education from "./Education";
import "./styles/Resume.scss";

const jobs = JOBS;
const education = EDUCATION;
function Resume() {
    return (<div>
        <div className="collapsibleSection">
            <h2>Work Experience</h2>
            {jobs.map((job: IJobInfo, _: number) => <Job jobInfo={job}/>)}
        </div>
        <div style={{height: 20}}/>
        <div className="collapsibleSection">
            <h2>Education</h2>
            {education.map((eduInfo: IEducationInfo, _: number) => <Education educationInfo={eduInfo}/>)}
        </div>
    </div>
    );
}

export default Resume;
