// geoffreywild-website-react/src/components/Education.tsx
import React from "react";
import { IEducationInfo } from "./models/education.models";
import ResumeDateRange from "./ResumeDateRange";
import ResumeInfoList from "./ResumeInfoList";

interface IEducationProps {
    educationInfo: IEducationInfo;
}

const Education: React.SFC<IEducationProps> = (props: IEducationProps) => {
    const education = props.educationInfo;
    return (
        <div>
            <h3>{education.institution}</h3>
            <div className="institutionInfo">
                {education.resumeInfo.location} / <ResumeDateRange dateStart={education.resumeInfo.dateStart} dateEnd={education.resumeInfo.dateEnd} />
            </div>

            {education.degree && education.major ? <div>{education.degree} / {education.major}</div> : null }

            <ResumeInfoList infoList={education.resumeInfo.infoList} />
        </div>
    );
}

export default Education;

// geoffreywild-website/src/app/education/education.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { IEducationInfo } from './education.models';

@Component({
  selector: 'app-education',
  templateUrl: './education.component.html',
})
export class EducationComponent implements OnInit {

  @Input() educationModel: IEducationInfo;
  constructor() { }

  ngOnInit() {
  }

}

<h3>{{educationModel.institution}}</h3>
<div class="institutionInfo">
    {{educationModel.resumeInfo.location}} / {{educationModel.resumeInfo.dateStart | date:"MMM yyyy"}} - {{educationModel.resumeInfo.dateEnd | date:"MMM yyyy"}}
</div>
<div *ngIf="educationModel.degree && educationModel.major" class="collegeEducation">
    {{educationModel.degree}} / {{educationModel.major}}
</div>
<div class="experienceInfo" *ngIf="educationModel.resumeInfo.infoList">
    <ul>
        <li *ngFor="let experience of educationModel.resumeInfo.infoList">
            {{experience}}
        </li>
    </ul>
</div>
