// geoffreywild-website/src/app/resume/resume.component.ts
import { Component, OnInit } from '@angular/core';

import { JOBS } from '../../data/jobs';
import { IJobInfo } from '../job/job.models';
import { IEducationInfo } from '../education/education.models';
import { EDUCATION } from 'src/data/education';

@Component({
  selector: 'app-resume',
  templateUrl: './resume.component.html',
  styleUrls: ['./resume.component.scss']
})
export class ResumeComponent implements OnInit {

  public jobs: IJobInfo[] = JOBS;
  public education: IEducationInfo[] = EDUCATION;
  public isWorkSectionCollapsed: boolean;
  public isEducationSectionCollapsed: boolean;

  constructor() {
    this.isWorkSectionCollapsed = true;
    this.isEducationSectionCollapsed = true;
  }

  ngOnInit() {
  }

}

<h1>Resume</h1>

<div>
  <div class="expandButton" (click)="toggleAllSections()">{{toggleText}}</div>
</div>

<div>
  <div class="expandButton" (click)="toggleResumeSection(ResumeSectionType.work)">Work Experience</div>
  <div class="collapsibleSection" *ngIf="!isWorkSectionCollapsed">
    <app-job *ngFor="let job of jobs" [jobModel]="job">
    </app-job>
  </div>
</div>

<div>
  <div class="expandButton" (click)="toggleResumeSection(ResumeSectionType.education)">Education</div>
  <div class="collapsibleSection" *ngIf="!isEducationSectionCollapsed">
    <app-education *ngFor="let eduEntry of education" [educationModel]="eduEntry">
    </app-education>
  </div>
</div>

// geoffreywild-website-react/src/components/Resume.tsx
import React, { useState } from "react";

import Job from "./Job";
import Education from "./Education";

import {EDUCATION} from "../data/education";
import { JOBS } from "../data/jobs";
import { IEducationInfo } from "./models/education.models";
import { IJobInfo } from "./models/job.models";
import "./styles/Resume.scss";

const jobs = JOBS;
const education = EDUCATION;


function Resume() {
    const [workExpanded, setWorkExpanded] = useState(true);
    const [educationExpanded, setEducationExpanded] = useState(true);

    return (<div>
        <div className="expandButton" onClick={() => setWorkExpanded(!workExpanded)}>Work Experience</div>
        {workExpanded ? <div className="collapsibleSection">{jobs.map((job: IJobInfo) => <Job jobInfo={job}/>)}</div> : <div />}
        <div className="expandButton" onClick={() => setEducationExpanded(!educationExpanded)}>Education</div>
        {educationExpanded ? <div className="collapsibleSection">{education.map((eduInfo: IEducationInfo) => <Education educationInfo={eduInfo}/>)}</div> : null}
    </div>
    );
}

export default Resume;
